<<<<<<< HEAD
// filepath: /Users/mb/Projects/my-cli-app/docker-compose.yml
=======
>>>>>>> f1f5527 (All changes: static assets, Docker, Go, and UI polish)
version: '3.8'
services:
  llm:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  jazzman:
    build: .
    environment:
      - LLM_API_URL=http://llm:11434
    depends_on:
      - llm
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ollama-data:
